version: '3'

services:

  postgres:
    container_name: postgresql
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mentor4you
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mentor4you_db
    networks:
      - common

  backend:
    container_name: backend_mentor4you
    image: backend
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    environment:
      SERVER_PORT: 8080
    networks:
      - common

networks:
  common:
    driver: bridge
