version: '3'

services:

  rabbitmq:
    container_name: activemq
    image: rmohr/activemq
    restart: always
    ports:
      - "61616:61616" # JMS
      - "8161:8161" # Web UI
    networks:
      - common

  auth_microservice:
    container_name: auth-microservice
    restart: always
    build:
      context: AuthMicroservice
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - "rabbitmq"
    environment:
      SERVER_PORT: 8080
      DB_TYPE: embedded
      DB_NAME: mentor4you_db
      DB_USER: mentor4you
      DB_PASSWORD: 1234
    networks:
      - common

  mime_content_microservice:
    container_name: mime-content-microservice
    restart: always
    build:
      context: MimeContentMicroservice
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "rabbitmq"
    environment:
      SERVER_PORT: 8080
      DB_TYPE: embedded
      DB_NAME: mentor4you_db
      DB_USER: mentor4you
      DB_PASSWORD: 1234
    networks:
      - common

  category_microservice:
    container_name: category-microservice
    restart: always
    build:
      context: CategoryMicroservice
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - "rabbitmq"
    environment:
      SERVER_PORT: 8080
      DB_TYPE: embedded
      DB_NAME: mentor4you_db
      DB_USER: mentor4you
      DB_PASSWORD: 1234
    networks:
      - common

  admin_microservice:
    container_name: admin-microservice
    restart: always
    build:
      context: SpringBootAdminMicroservice
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      SERVER_PORT: 8080
    networks:
      - common

networks:
  common:
    driver: bridge
