server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  #SQLDatabase setting
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:/sql/data.sql

  rabbitmq:
    host: rabbitmq
    port: 5672

web:
  auth-microservice:
    schema: http
    host: auth-microservice
    port: 8080
  category-microservice:
    schema: http
    host: category-microservice
    port: 8080

credentials:
  email: mimeservice@gmail.com
  password: 123Password