version: '3'

services:

  mongodb:
    container_name: mongodb
    image: "mongo:5.0"
    restart: always
    ports:
      - "27018:27017"
      - "28017:28017"
    environment:
      MONGO_INITDB_DATABASE: mentor4you_db

  backend:
    container_name: backend_mentor4you
    image: backend
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - "mongodb"
    environment:
    SERVER_PORT: 8081
      MONGODB_URI:mongodb: //mongodb:27017/mentor4you_db
      MONGODB_STATUS_HOST: mongodb
      MONGODB_STATUS_PORT: 28017
    networks:
      - common

networks:
  common:
    driver: bridge
