server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user_microservice_route
          uri: http://user-microservice:8080
          predicates:
            - Path=/api/users/**, /api/mentors/**, /api/mentees/**

        - id: review_microservice_route
          uri: http://review-microservice:8080
          predicates:
            - Path=/api/reviews/**

        - id: cooperation_microservice_route
          uri: http://cooperation-microservice:8080
          predicates:
            - Path=/api/categories/**, /api/pricelists/**

        - id: auth_microservice_route
          uri: http://auth-microservice:8080
          predicates:
            - Path=/api/auth/**, /api/registration/**

management:
  endpoints:
    web:
      exposure:
        include: "*"