server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  #SQLDatabase setting
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:/sql/data.sql
  boot:
    admin:
      client:
        url: "http://admin-microservice:8080"

management:
  endpoints:
    web:
      exposure:
        include: '*'

activemq:
  protocol: tcp
  host: rabbitmq
  port: 61616

web:
  auth-microservice:
    schema: http
    host: auth-microservice
    port: 8080